2d noise kernel
Matt-Ord/surface_potential_analysis pull request #51
Opened 2024-08-22 14:19 UTC by Winnie08L

2024-08-22 16:17 UTC, Winnie08L commented
in build.py build_isotropic_kernels_frmo_function(), get attributeError if use the build_kernel_from function (the one defined previously for 1d) cuz the basis is not the right type, need to fix that

2024-08-28 13:18 UTC, Matt-Ord requested changes

2024-08-28 13:18 UTC, Matt-Ord commented on surface_potential_analysis/kernel/build.py
> +    return tuple(build_isotropic_kernel_from_function(basis_i, fn) for basis_i in basis)
add a build_isotropic_kernel() which works on a flat axis to sort these type issues, also add a build_isotropic_kernel_stacked_from_function which gets the full stacked kernel like build_isotropic_kernel_from_function currently does

2024-08-28 13:18 UTC, Matt-Ord commented on surface_potential_analysis/kernel/build.py
> +    return tuple(build_isotropic_kernel_from_function(basis_i, fn) for basis_i in basis)
StackedBasis is not necessarily iterable!

2024-08-28 13:18 UTC, Matt-Ord commented on surface_potential_analysis/kernel/gaussian.py
> +def get_separate_gaussian_isotropic_noise_kernel(
should this be part of the public interface? Probably not...

2024-08-28 13:18 UTC, Matt-Ord commented on surface_potential_analysis/kernel/kernel.py
> +def outer_product(*arrays):
I don't think this should be part of the public interface

2024-08-28 13:18 UTC, Matt-Ord commented on surface_potential_analysis/kernel/kernel.py
> +def get_full_kernel_from_independent(
move to build.py. Be more consistent in naming these kernels - are they 'inependent kernels' or 'seperate kernels'. rename get_separate_gaussian_isotropic_noise_kernel accordingly. I would maybe call them something like axis kernels

2024-08-28 13:18 UTC, Matt-Ord commented on surface_potential_analysis/kernel/plot.py
> +def _get_noise_kernel_percentage_error(
needs a rebase i think?

2024-09-01 12:10 UTC, Matt-Ord approved these changes
Well done! Was all pretty much working.

2024-09-01 12:10 UTC, merged